/**
 * Tests for src/modules/images/upload.service.ts
 *
 * Strategy: unit-test the service in isolation.
 * - The storage driver and repository layer are fully mocked so no real
 *   filesystem writes or MongoDB connections are needed.
 * - Sharp is NOT mocked — real image inspection is used. A 1×1 JPEG generated
 *   by Sharp itself serves as the valid test fixture, keeping the test
 *   independent of any committed binary file.
 */
import { describe, it, expect, vi, beforeAll, beforeEach } from 'vitest';
import sharp from 'sharp';
import type { FastifyBaseLogger } from 'fastify';
import { PayloadTooLargeError, UnsupportedMediaTypeError } from '../../src/lib/errors';
import { MAX_UPLOAD_BYTES } from '../../src/modules/images/upload.service';

// ─── Module Mocks ─────────────────────────────────────────────────────────────
// vi.mock() calls are hoisted to the top of the compiled output by Vitest, so
// they run before any imports are resolved. The factory functions are evaluated
// lazily — spies can be reassigned in beforeEach without re-mocking.

vi.mock('../../src/storage/index', () => ({
  storage: {
    save:   vi.fn().mockResolvedValue(undefined),
    getUrl: vi.fn().mockReturnValue('http://localhost:3000/files/originals/abc.jpg'),
  },
  originalKey:            vi.fn().mockReturnValue('originals/testhash.jpg'),
  derivedKey:             vi.fn(),
  sourceIdFromDerivedKey: vi.fn(),
}));

vi.mock('../../src/modules/images/asset.repository', () => ({
  findOriginalByHash:   vi.fn().mockResolvedValue(null),
  createOriginalAsset:  vi.fn(),
  findOrCreateDerivedAsset: vi.fn(),
  findAssetById:        vi.fn(),
  softDeleteAsset:      vi.fn(),
  updateAssetStatus:    vi.fn(),
  listAssets:           vi.fn(),
}));

// ─── Lazy imports (after mocks are in place) ──────────────────────────────────
// Import these after vi.mock() so they receive the mocked versions.
const { uploadOriginal } = await import('../../src/modules/images/upload.service');
const { storage }        = await import('../../src/storage/index');
const { findOriginalByHash, createOriginalAsset } =
  await import('../../src/modules/images/asset.repository');

// ─── Fixtures ─────────────────────────────────────────────────────────────────

/** Minimal 1×1 red JPEG generated by Sharp — the smallest valid JPEG Sharp accepts. */
let validJpegBuffer: Buffer;

/** A mock asset returned by the createOriginalAsset repository stub. */
const mockAsset = {
  _id:       { toString: () => '507f1f77bcf86cd799439011' },
  type:      'original' as const,
  status:    'ready' as const,
  createdAt: new Date('2024-01-01T00:00:00.000Z'),
  updatedAt: new Date('2024-01-01T00:00:00.000Z'),
};

/** A no-op logger — prevents Pino output noise in test output. */
const mockLog = {
  info:  vi.fn(),
  warn:  vi.fn(),
  error: vi.fn(),
  debug: vi.fn(),
  trace: vi.fn(),
  fatal: vi.fn(),
  child: vi.fn(),
} as unknown as FastifyBaseLogger;

// ─── Setup ────────────────────────────────────────────────────────────────────

beforeAll(async () => {
  validJpegBuffer = await sharp({
    create: { width: 1, height: 1, channels: 3, background: { r: 255, g: 0, b: 0 } },
  })
    .jpeg()
    .toBuffer();
});

beforeEach(() => {
  vi.clearAllMocks();

  // Default happy-path stubs — individual tests override with mockResolvedValueOnce
  vi.mocked(findOriginalByHash).mockResolvedValue(null);
  vi.mocked(createOriginalAsset).mockResolvedValue(mockAsset as never);
  vi.mocked(storage.save).mockResolvedValue(undefined);
  vi.mocked(storage.getUrl).mockReturnValue('http://localhost:3000/files/originals/testhash.jpg');
});

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('uploadOriginal', () => {
  // ── Successful upload ──────────────────────────────────────────────────────

  describe('successful upload', () => {
    it('returns the newly created asset with deduplicated: false', async () => {
      const result = await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'photo.jpg' },
        mockLog,
      );

      expect(result.deduplicated).toBe(false);
      expect(result.asset).toBe(mockAsset);
    });

    it('saves the file to storage exactly once', async () => {
      await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'photo.jpg' },
        mockLog,
      );

      expect(storage.save).toHaveBeenCalledOnce();
    });

    it('creates exactly one asset record in the database', async () => {
      await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'photo.jpg' },
        mockLog,
      );

      expect(createOriginalAsset).toHaveBeenCalledOnce();
    });

    it('passes correct file metadata to createOriginalAsset', async () => {
      await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'my-photo.jpg' },
        mockLog,
      );

      const [input] = vi.mocked(createOriginalAsset).mock.calls[0]!;
      expect(input.file.originalName).toBe('my-photo.jpg');
      expect(input.file.mimeType).toBe('image/jpeg');
      expect(input.file.sizeBytes).toBe(validJpegBuffer.byteLength);
      expect(input.file.width).toBe(1);
      expect(input.file.height).toBe(1);
      // SHA-256 is always a 64-char hex string
      expect(input.file.hash).toMatch(/^[a-f0-9]{64}$/);
    });

    it('stores the file under a key derived from the content hash', async () => {
      await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'photo.jpg' },
        mockLog,
      );

      // The key passed to storage.save must match the key from originalKey()
      const [, savedKey] = vi.mocked(storage.save).mock.calls[0]!;
      expect(savedKey).toBe('originals/testhash.jpg');
    });

    it('accepts a valid PNG image', async () => {
      const pngBuffer = await sharp({
        create: { width: 2, height: 2, channels: 4, background: { r: 0, g: 0, b: 255, alpha: 1 } },
      })
        .png()
        .toBuffer();

      const result = await uploadOriginal(
        { buffer: pngBuffer, originalName: 'icon.png' },
        mockLog,
      );

      expect(result.deduplicated).toBe(false);
      const [input] = vi.mocked(createOriginalAsset).mock.calls[0]!;
      expect(input.file.mimeType).toBe('image/png');
    });

    it('accepts a valid WebP image', async () => {
      const webpBuffer = await sharp({
        create: { width: 1, height: 1, channels: 3, background: { r: 0, g: 255, b: 0 } },
      })
        .webp()
        .toBuffer();

      const result = await uploadOriginal(
        { buffer: webpBuffer, originalName: 'image.webp' },
        mockLog,
      );

      expect(result.deduplicated).toBe(false);
      const [input] = vi.mocked(createOriginalAsset).mock.calls[0]!;
      expect(input.file.mimeType).toBe('image/webp');
    });
  });

  // ── Deduplication ──────────────────────────────────────────────────────────

  describe('deduplication', () => {
    it('returns the existing asset with deduplicated: true when hash matches', async () => {
      const existingAsset = {
        ...mockAsset,
        _id: { toString: () => 'aabbccddeeff001122334455' },
      };
      vi.mocked(findOriginalByHash).mockResolvedValueOnce(existingAsset as never);

      const result = await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'photo.jpg' },
        mockLog,
      );

      expect(result.deduplicated).toBe(true);
      expect(result.asset).toBe(existingAsset);
    });

    it('skips storage.save when the file is deduplicated', async () => {
      vi.mocked(findOriginalByHash).mockResolvedValueOnce(mockAsset as never);

      await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'photo.jpg' },
        mockLog,
      );

      expect(storage.save).not.toHaveBeenCalled();
    });

    it('skips createOriginalAsset when the file is deduplicated', async () => {
      vi.mocked(findOriginalByHash).mockResolvedValueOnce(mockAsset as never);

      await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'photo.jpg' },
        mockLog,
      );

      expect(createOriginalAsset).not.toHaveBeenCalled();
    });
  });

  // ── Invalid MIME type ──────────────────────────────────────────────────────

  describe('invalid MIME type', () => {
    it('throws UnsupportedMediaTypeError for an arbitrary binary buffer', async () => {
      const notAnImage = Buffer.from('this is definitely not an image');

      await expect(
        uploadOriginal({ buffer: notAnImage, originalName: 'file.bin' }, mockLog),
      ).rejects.toThrow(UnsupportedMediaTypeError);
    });

    it('throws UnsupportedMediaTypeError for a plain-text file disguised as JPEG', async () => {
      const fakeJpeg = Buffer.from('<?php echo "hello"; ?>');

      await expect(
        uploadOriginal({ buffer: fakeJpeg, originalName: 'evil.jpg' }, mockLog),
      ).rejects.toThrow(UnsupportedMediaTypeError);
    });

    it('throws UnsupportedMediaTypeError for an empty buffer', async () => {
      await expect(
        uploadOriginal({ buffer: Buffer.alloc(0), originalName: 'empty' }, mockLog),
      ).rejects.toThrow(UnsupportedMediaTypeError);
    });

    it('does not call storage.save for an invalid file', async () => {
      const notAnImage = Buffer.from('not an image');

      await expect(
        uploadOriginal({ buffer: notAnImage, originalName: 'file.txt' }, mockLog),
      ).rejects.toThrow();

      expect(storage.save).not.toHaveBeenCalled();
    });

    it('does not call createOriginalAsset for an invalid file', async () => {
      const notAnImage = Buffer.from('not an image');

      await expect(
        uploadOriginal({ buffer: notAnImage, originalName: 'file.txt' }, mockLog),
      ).rejects.toThrow();

      expect(createOriginalAsset).not.toHaveBeenCalled();
    });
  });

  // ── Oversized file ─────────────────────────────────────────────────────────

  describe('oversized file', () => {
    it('throws PayloadTooLargeError when buffer exceeds MAX_UPLOAD_BYTES', async () => {
      // Allocate 1 byte over the limit. Buffer.alloc uses OS zero-pages so
      // this does not actually occupy physical memory — just virtual address space.
      const oversized = Buffer.alloc(MAX_UPLOAD_BYTES + 1);

      await expect(
        uploadOriginal({ buffer: oversized, originalName: 'huge.jpg' }, mockLog),
      ).rejects.toThrow(PayloadTooLargeError);
    });

    it('does not invoke Sharp for an oversized buffer', async () => {
      // Sharp should never be reached — the size check is the first gate.
      // We verify this indirectly: storage.save is also not called, meaning
      // execution stopped before any I/O.
      const oversized = Buffer.alloc(MAX_UPLOAD_BYTES + 1);

      await expect(
        uploadOriginal({ buffer: oversized, originalName: 'huge.jpg' }, mockLog),
      ).rejects.toThrow(PayloadTooLargeError);

      expect(storage.save).not.toHaveBeenCalled();
      expect(createOriginalAsset).not.toHaveBeenCalled();
    });

    it('accepts a buffer exactly at the size limit', async () => {
      // A buffer exactly at the limit must NOT be rejected by the size check.
      // It will fail later (Sharp cannot parse 50MB of zeros), but the error
      // must be UnsupportedMediaTypeError, not PayloadTooLargeError.
      const atLimit = Buffer.alloc(MAX_UPLOAD_BYTES);

      await expect(
        uploadOriginal({ buffer: atLimit, originalName: 'at-limit.jpg' }, mockLog),
      ).rejects.toThrow(UnsupportedMediaTypeError);
    });
  });

  // ── Hash determinism ───────────────────────────────────────────────────────

  describe('content hash', () => {
    it('computes the same hash for identical buffers across two calls', async () => {
      let hash1: string | undefined;
      let hash2: string | undefined;

      vi.mocked(createOriginalAsset).mockImplementation(async (input) => {
        hash1 = input.file.hash;
        return mockAsset as never;
      });

      await uploadOriginal(
        { buffer: validJpegBuffer, originalName: 'first.jpg' },
        mockLog,
      );

      // Second call: dedup is off (findOriginalByHash returns null) but we
      // need a fresh mock implementation to capture the second hash.
      vi.mocked(createOriginalAsset).mockImplementation(async (input) => {
        hash2 = input.file.hash;
        return mockAsset as never;
      });
      // Dedup check: first call stored nothing visible to the mock — still null
      vi.mocked(findOriginalByHash).mockResolvedValueOnce(null);

      await uploadOriginal(
        { buffer: Buffer.from(validJpegBuffer), originalName: 'second.jpg' },
        mockLog,
      );

      expect(hash1).toBeDefined();
      expect(hash2).toBeDefined();
      expect(hash1).toBe(hash2);
    });
  });
});
